### ISSUE TITLE
IndexError: Traceback (most recent call last):

### ISSUE THREAD

**Issue by MyrnaQiu** [jakeoung/u-net_pytorch#4]
Hello, this error occurred when I input some kaggle2016nerve pictures
IndexError: Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 40, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 40, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/dataset.py", line 46, in __getitem__
    img_path, gt_path = self.train_set_path[idx]
IndexError: list index out of range
I appreciated any suggestion to fix this error. Thanks!

**Comment by MyrnaQiu** [comment]
I have solved it,just change the "def __len__(self):" of class kaggle2016nerve(data.Dataset),thanks!
